### ISSUE TITLE
Support private repositories (travis-ci.com)

### ISSUE THREAD

**Issue by Deilan** [artemgurzhii/TravisCI-Telegam-Bot#10]
Please add a support of private repositories, which are managed at https://travis-ci.com.

![image](https://user-images.githubusercontent.com/4777512/28078538-dbabbcb8-666d-11e7-88f0-0fdc3effc7bd.png)

**Comment by artemgurzhii** [comment]
@Deilan This will require users to provide their logins and passwords, which I don't think anyone would do or should do for the security reasons.
