### ISSUE TITLE
bot not working

### ISSUE THREAD

**Issue by therickys93** [artemgurzhii/TravisCI-Telegam-Bot#11]
your bot does not reply to me

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by artemgurzhii** [comment]
@therickys93 now?

**Comment by therickys93** [comment]
yes now it is working

_Sent from my Huawei ALE-L21 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by artemgurzhii** [comment]
Great!
