### ISSUE TITLE
Feature request: hyperlink to the build status in the Telegram message

### ISSUE THREAD

**Issue by oncleben31** [artemgurzhii/TravisCI-Telegam-Bot#2]
First thank you for your bot. It's really useful!

It could be interesting to have in the Telegram notification the hyperlink linking the build status on the travis-ci.org site (ex: https://travis-ci.org/oncleben31/oncleben31.github.io/builds/169655914)

**Comment by artemgurzhii** [comment]
Closing #2 via b9e6ef5

**Comment by oncleben31** [comment]
Tested and Okay. Thanks.
