### ISSUE TITLE
Prettify build message

### ISSUE THREAD

**Issue by ramoona** [artemgurzhii/TravisCI-Telegam-Bot#7]
Hey! Thx for useful bot :) Maybe build messages could be a little bit more evident? Something like this:

![default](https://cloud.githubusercontent.com/assets/7067080/24237385/1afc2a1e-0fb7-11e7-9462-f8464e4c4bdc.PNG)

It's possible to use markdown for links.

**Comment by artemgurzhii** [comment]
Hey, I think that would be a great improvement and I definitely like this way, will fix soon.

**Comment by ramoona** [comment]
This icons are just emoji :) ✅ ❌ you can add it straight to text. Also there is a [link ](https://core.telegram.org/bots/api#markdown-style)to telegram markdown,

**Comment by artemgurzhii** [comment]
@ramoona Thanks for help)
