### ISSUE TITLE
Option to only get notifications on failed builds

### ISSUE THREAD

**Issue by TobsCore** [artemgurzhii/TravisCI-Telegam-Bot#8]
It would be really useful to have a setting that would let us select, whether we get informed on all build updates, or only failing ones.

Successful builds aren't as important as failing ones to most developers, so this Options would be really appreciated.

**Comment by artemgurzhii** [comment]
Thanks)

**Comment by TobsCore** [comment]
Wow nice, that was fast. Thank you for your amazing work!
